# The pandas Series and DataFrame

In [1]:
# import pandas
import pandas as pd

# and NumPy
import numpy as np

# Set some Pandas options
pd.set_option("display.notebook_repr_html", False)
pd.set_option("display.max_columns", 8)
pd.set_option("display.max_rows", 8)

## Creating a Series and accessing elements

In [2]:
# create a Series from a NumPy array of random values
np.random.seed(1)
s = pd.Series(np.random.randn(100))
s

0     1.624345
1    -0.611756
2    -0.528172
3    -1.072969
        ...   
96   -0.343854
97    0.043597
98   -0.620001
99    0.698032
dtype: float64

In [3]:
# select item with matching label of 2
s[2]

-0.5281717522634557

In [4]:
# selected elements at positions 2, 5, and 20
s[[2, 5, 20]]

2    -0.528172
5    -2.301539
20   -1.100619
dtype: float64

In [5]:
# slice the Series
s[3:8]

3   -1.072969
4    0.865408
5   -2.301539
6    1.744812
7   -0.761207
dtype: float64

In [6]:
s.head()

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
dtype: float64

In [7]:
s.tail()

95    0.077340
96   -0.343854
97    0.043597
98   -0.620001
99    0.698032
dtype: float64

In [8]:
s.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype='int64')

In [9]:
s.values

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521,
       -1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547,
       -0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
       -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
       -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
       -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311,
        0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
        0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116,
       -0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
       -0.07557171,  1.13162939,  1.51981682,  2.18557541, -1.39

In [10]:
# specify an index at creation time
s2 = pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
# create a Sereis from a Python dict
s2 = pd.Series({"a": 1, "b": 2, "c": 3, "d": 4, "e": 5})
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

## Size, shape, uniqueness and counts of values

In [12]:
# create a series
s = pd.Series([5, 0, 1, 1, 2, 3, 4, 5, 6, np.nan])
len(s)

10

In [13]:
# reports the shape, which is a tuple with len in the first value
s.shape

(10,)

In [14]:
# .count() is the number of non NaN values
s.count()

9

In [15]:
# all unique values
s.unique()

array([  5.,   0.,   1.,   2.,   3.,   4.,   6.,  nan])

In [16]:
# all unique values and their counts
s.value_counts()

5    2
1    2
6    1
4    1
3    1
2    1
0    1
dtype: int64

## Alignment via index labels

In [17]:
s3 = pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
s3

a    1
b    2
c    3
d    4
dtype: int64

In [18]:
s4 = pd.Series([4, 3, 2, 1], index=["d", "c", "b", "a"])
s4

d    4
c    3
b    2
a    1
dtype: int64

In [19]:
# add s3 and s4
s3 + s4

a    2
b    4
c    6
d    8
dtype: int64

In [20]:
# see how different from adding numpy arrays
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1 + a2

array([5, 5, 5, 5])

# Creating a DataFrame

In [21]:
# create a DataFrame from a 2-d ndarray
pd.DataFrame(np.array([[10, 11], [20, 21]]))

    0   1
0  10  11
1  20  21

In [22]:
# create a DataFrame for a list of Series objects
df1 = pd.DataFrame([pd.Series(np.arange(10, 15)), pd.Series(np.arange(15, 20))])
df1

    0   1   2   3   4
0  10  11  12  13  14
1  15  16  17  18  19

In [23]:
# what's the shape of this DataFrame
df1.shape  # it is two rows by 5 columns

(2, 5)

In [24]:
# specify column names
df = pd.DataFrame(np.array([[10, 11], [20, 21]]), columns=["a", "b"])
df

    a   b
0  10  11
1  20  21

In [25]:
# what are names of the columns?
df.columns

Index([u'a', u'b'], dtype='object')

In [26]:
df.columns = ["c1", "c2"]
df

   c1  c2
0  10  11
1  20  21

In [27]:
# create a DataFrame with named columns and rows
df = pd.DataFrame(np.array([[0, 1], [2, 3]]), columns=["c1", "c2"], index=["r1", "r2"])
df

    c1  c2
r1   0   1
r2   2   3

In [28]:
# retrieve the index of the DataFrame
df.index

Index([u'r1', u'r2'], dtype='object')

In [29]:
df.values

array([[0, 1],
       [2, 3]])

In [30]:
# create a DataFrame with two Series objects
# and a dictionary
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
pd.DataFrame({"c1": s1, "c2": s2})

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

In [31]:
# demonstrate alignment during creation
s3 = pd.Series(np.arange(12, 14), index=[1, 2])
pd.DataFrame({"c1": s1, "c2": s2, "c3": s3})

   c1  c2  c3
0   1   6 NaN
1   2   7  12
2   3   8  13
3   4   9 NaN
4   5  10 NaN

## Example data

In [32]:
# read in the data and print the first five rows
# use the Symbol column as the index, and
# only read in columns in positions 0, 2, 3, 7
sp500 = pd.read_csv("sp500.csv", index_col="Symbol", usecols=[0, 2, 3, 7])

In [33]:
# peek at the first 5 rows of the data using .head()
sp500.head()

                        Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [34]:
# examine the index
sp500.index

Index([u'MMM', u'ABT', u'ABBV', u'ACN', u'ACE', u'ACT', u'ADBE', u'AES', u'AET', u'AFL', u'A', u'GAS', u'APD', u'ARG', u'AKAM', u'AA', u'ALXN', u'ATI', u'ALLE', u'AGN', u'ADS', u'ALL', u'ALTR', u'MO', u'AMZN', u'AEE', u'AEP', u'AXP', u'AIG', u'AMT', u'AMP', u'ABC', u'AME', u'AMGN', u'APH', u'APC', u'ADI', u'AON', u'APA', u'AIV', u'AAPL', u'AMAT', u'ADM', u'AIZ', u'T', u'ADSK', u'ADP', u'AN', u'AZO', u'AVB', u'AVY', u'AVP', u'BHI', u'BLL', u'BAC', u'BCR', u'BAX', u'BBT', u'BEAM', u'BDX', u'BBBY', u'BMS', u'BRK-B', u'BBY', u'BIIB', u'BLK', u'HRB', u'BA', u'BWA', u'BXP', u'BSX', u'BMY', u'BRCM', u'BF-B', u'CA', u'CVC', u'COG', u'CAM', u'CPB', u'COF', u'CAH', u'CFN', u'KMX', u'CCL', u'CAT', u'CBG', u'CBS', u'CELG', u'CNP', u'CTL', u'CERN', u'CF', u'CHRW', u'CHK', u'CVX', u'CMG', u'CB', u'CI', u'CINF', u'CTAS', ...], dtype='object')

### Selecting columns of a DataFrame

In [35]:
# get first and second columns (1 and 2) by location
sp500[[1, 2]].head(3)

         Price  Book Value
Symbol                    
MMM     141.14      26.668
ABT      39.60      15.573
ABBV     53.95       2.954

In [36]:
# just the price column
sp500[[1]].head(3)

         Price
Symbol        
MMM     141.14
ABT      39.60
ABBV     53.95

In [37]:
# get price column by name
# result is a Series
sp500["Price"]

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
         ...  
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, dtype: float64

In [38]:
# get Price and Sector columns
# since a list is passed, result is a DataFrame
sp500[["Price", "Sector"]]

         Price                  Sector
Symbol                                
MMM     141.14             Industrials
ABT      39.60             Health Care
ABBV     53.95             Health Care
ACN      79.79  Information Technology
...        ...                     ...
YUM      74.77  Consumer Discretionary
ZMH     101.84             Health Care
ZION     28.43              Financials
ZTS      30.53             Health Care

[500 rows x 2 columns]

In [39]:
# attribute access of column by name
sp500.Price

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
         ...  
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, dtype: float64

## Selecting rows of a DataFrame 

### Slicing using the [] operator

In [40]:
# first five rows
sp500[:3]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954

In [41]:
# XYL through YUM labels
sp500["XYL":"YUM"]

                        Sector  Price  Book Value
Symbol                                           
XYL                Industrials  38.42      12.127
YHOO    Information Technology  35.02      12.768
YUM     Consumer Discretionary  74.77       5.147

### Selecting rows by index label and location: .loc[] and .iloc[]

In [42]:
# get row with label MMM
# returned as a Series
sp500.loc["MMM"]

Sector        Industrials
Price              141.14
Book Value         26.668
Name: MMM, dtype: object

In [43]:
# rows with label MMM and MSFT
# this is a DataFrame result
sp500.loc[["MMM", "MSFT"]]

                        Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
MSFT    Information Technology   40.12      10.584

In [44]:
# get rows in location 0 and 2
sp500.iloc[[0, 2]]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABBV    Health Care   53.95       2.954

In [45]:
# get the location of MMM and A in the index
i1 = sp500.index.get_loc("MMM")
i2 = sp500.index.get_loc("A")
i1, i2

(0, 10)

In [46]:
# and get the rows
sp500.iloc[[i1, i2]]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
A       Health Care   56.18      16.928

### Selecting rows by index label and/or location: .ix[]

In [47]:
# by label
sp500.ix[["MSFT", "ZTS"]]

                        Sector  Price  Book Value
Symbol                                           
MSFT    Information Technology  40.12      10.584
ZTS                Health Care  30.53       2.150

In [48]:
# by location
sp500.ix[[10, 200, 450]]

                  Sector  Price  Book Value
Symbol                                     
A            Health Care  56.18      16.928
GIS     Consumer Staples  53.81      10.236
TRV           Financials  92.86      73.056

### Scalar lookup by label or location using .at[] and .iat[] 

In [49]:
# by label in both the index and column
sp500.at["MMM", "Price"]

141.13999999999999

In [50]:
# by location.  Row 0, column 1
sp500.iat[0, 1]

141.13999999999999

## Selecting rows using Boolean selection

In [51]:
# what rows have a price < 100?
sp500.Price < 100

Symbol
MMM     False
ABT      True
ABBV     True
ACN      True
        ...  
YUM      True
ZMH     False
ZION     True
ZTS      True
Name: Price, dtype: bool

In [52]:
# now get the rows with Price < 100
sp500[sp500.Price < 100]

                        Sector  Price  Book Value
Symbol                                           
ABT                Health Care  39.60      15.573
ABBV               Health Care  53.95       2.954
ACN     Information Technology  79.79       8.326
ADBE    Information Technology  64.30      13.262
...                        ...    ...         ...
YHOO    Information Technology  35.02      12.768
YUM     Consumer Discretionary  74.77       5.147
ZION                Financials  28.43      30.191
ZTS                Health Care  30.53       2.150

[407 rows x 3 columns]

In [53]:
# get only the Price where Price is < 10 and > 0
sp500[(sp500.Price < 10) & (sp500.Price > 0)][["Price"]]

        Price
Symbol       
FTR      5.81
HCBK     9.80
HBAN     9.10
SLM      8.82
WIN      9.38

## Arithmetic on a DataFrame

In [54]:
# set the seed to allow replicatable results
np.random.seed(123456)
# create the DataFrame
df = pd.DataFrame(np.random.randn(5, 4), columns=["A", "B", "C", "D"])
df

          A         B         C         D
0  0.469112 -0.282863 -1.509059 -1.135632
1  1.212112 -0.173215  0.119209 -1.044236
2 -0.861849 -2.104569 -0.494929  1.071804
3  0.721555 -0.706771 -1.039575  0.271860
4 -0.424972  0.567020  0.276232 -1.087401

In [55]:
# multiply everything by 2
df * 2

          A         B         C         D
0  0.938225 -0.565727 -3.018117 -2.271265
1  2.424224 -0.346429  0.238417 -2.088472
2 -1.723698 -4.209138 -0.989859  2.143608
3  1.443110 -1.413542 -2.079150  0.543720
4 -0.849945  1.134041  0.552464 -2.174801

In [56]:
df - df.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1  0.743000  0.109649  1.628267  0.091396
2 -1.330961 -1.821706  1.014129  2.207436
3  0.252443 -0.423908  0.469484  1.407492
4 -0.894085  0.849884  1.785291  0.048232

In [57]:
# get rows 1 through three, and only B, C columns
subframe = df[1:4][["B", "C"]]
# we have extracted a little square in the middle of df
subframe

          B         C
1 -0.173215  0.119209
2 -2.104569 -0.494929
3 -0.706771 -1.039575

In [58]:
# demonstrate the alignment of the subtraction
df - subframe

    A   B   C   D
0 NaN NaN NaN NaN
1 NaN   0   0 NaN
2 NaN   0   0 NaN
3 NaN   0   0 NaN
4 NaN NaN NaN NaN

In [59]:
# get the A column
a_col = df["A"]
df.sub(a_col, axis=0)

   A         B         C         D
0  0 -0.751976 -1.978171 -1.604745
1  0 -1.385327 -1.092903 -2.256348
2  0 -1.242720  0.366920  1.933653
3  0 -1.428326 -1.761130 -0.449695
4  0  0.991993  0.701204 -0.662428

# Reindexing Series and DataFrame objects

In [60]:
# create a series of five random numbers
np.random.seed(1)
s = pd.Series(np.random.randn(5))
s

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
dtype: float64

In [61]:
# now set the index to alpha values
s.index = ["a", "b", "c", "d", "e"]
s

a    1.624345
b   -0.611756
c   -0.528172
d   -1.072969
e    0.865408
dtype: float64

In [62]:
# reindex the copy
s2 = s.reindex(["a", "c", "e", "g"])
# change the value at 'a'
s2["a"] = 0
s2

a    0.000000
c   -0.528172
e    0.865408
g         NaN
dtype: float64

In [63]:
s["a"]

1.6243453636632417

In [64]:
# Series objects with string and integer index types
# with the "same" values will not align
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])
s2 = pd.Series([3, 4, 5], index=["0", "1", "2"])
s1 + s2

0   NaN
1   NaN
2   NaN
0   NaN
1   NaN
2   NaN
dtype: float64

In [65]:
# demonstrate treating values at a specific type
s2.index = s2.index.values.astype(int)
s1 + s2

0    3
1    5
2    7
dtype: int64

In [66]:
# show reindexing with filling of NaN with a specified value
s2 = s.copy()
s2.reindex(["a", "f"], fill_value=0)

a    1.624345
f    0.000000
dtype: float64

In [67]:
# a Series to demonstrate reindexing
s3 = pd.Series(["red", "green", "blue"], index=[0, 3, 5])
s3

0      red
3    green
5     blue
dtype: object

In [68]:
# forward fill (last known value technique)
s3.reindex(np.arange(0, 7), method="ffill")

0      red
1      red
2      red
3    green
4    green
5     blue
6     blue
dtype: object

In [69]:
# demonstrate how backwards fill differs
s3.reindex(np.arange(0, 7), method="bfill")

0      red
1    green
2    green
3    green
4     blue
5     blue
6      NaN
dtype: object